apiVersion: apps/v1
kind: Deployment
metadata:
  name: daoducan-io-vn-website-deployment
  namespace: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daoducan-io-vn-website
  template:
    metadata:
      labels:
        app: daoducan-io-vn-website
    spec:
      containers:
        - name: daoducan-io-vn-website-container
          image: daoducan88/daoducan-io-vn-ci-cd-pipeline:1.0.0.12
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80